# Generated by Django 2.1.3 on 2018-11-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_not_working', models.CharField(max_length=16)),
                ('injury', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('dateTime', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('counter', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parts_id', models.ManyToManyField(to='AHLSROM.SpareParts')),
            ],
        ),
        migrations.AddField(
            model_name='machines',
            name='parts',
            field=models.ManyToManyField(to='AHLSROM.SpareParts'),
        ),
        migrations.AddField(
            model_name='issue',
            name='machine_id',
            field=models.ManyToManyField(to='AHLSROM.Machines'),
        ),
        migrations.AddField(
            model_name='issue',
            name='parts_id',
            field=models.ManyToManyField(to='AHLSROM.SpareParts'),
        ),
    ]
